### PR TITLE
Workaround for event loop is closed error

### LINKED ISSUE #25: TimeoutError is thrown on retrieval of own ip address
I encountered a new error stating: "Could not get a external IP.".

I took a look around to figure out if I can fix it or if I caused the error somehow. To me it looks like proxybroker tries to connect to "http://httpbin.org/ip" but the timeout of 3 seconds fails. I checked whether the mentioned website was working properly. It is up and running with fast response times.
I tried running proxybroker on a server, to check whether or not it is a local problem with the same error popping up.
The funny thing is sometimes proxybroker actually fetched a few proxies before the following error was thrown.

Do you have any idea what else could cause this error, but the website? And more important, how to fix this issue?

Any feedback is appreciated!

```
/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/aiohttp/client.py:494: DeprecationWarning: Use async with instead
  warnings.warn("Use async with instead", DeprecationWarning)
Traceback (most recent call last):
  File "/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/proxybroker/utils.py", line 101, in set_my_ip
    data = await resp.json()
  File "/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/async_timeout/__init__.py", line 44, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastian/PycharmProjects/testing/test/test_prox2.py", line 19, in <module>
    loop.run_until_complete(tasks)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/proxybroker/api.py", line 98, in find
    await set_my_ip(self._timeout, self._loop)
  File "/home/sebastian/PycharmProjects/STW/venv/lib/python3.5/site-packages/proxybroker/utils.py", line 103, in set_my_ip
    raise RuntimeError('Could not get an external IP. Error: %s' % e)
RuntimeError: Could not get an external IP. Error: 
Exception ignored in: <coroutine object show at 0x7f9b22cdd150>
Traceback (most recent call last):
  File "/home/sebastian/PycharmProjects/testing/test/test_prox2.py", line 7, in show
  File "/usr/lib/python3.5/asyncio/queues.py", line 170, in get
  File "/usr/lib/python3.5/asyncio/futures.py", line 227, in cancel
  File "/usr/lib/python3.5/asyncio/futures.py", line 242, in _schedule_callbacks
  File "/usr/lib/python3.5/asyncio/base_events.py", line 497, in call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
  File "/usr/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
RuntimeError: Event loop is closed


Process finished with exit code 1
```

### PR DESCRIPTION
**Pull request by gabrielgradinaru**
Fixes #25

### CODE REVIEW

**Comment by constverum** [comment]
As it seems to me the cause of #25 issue is that it's not always possible to get response from httpbin.org (for some reason), and `RuntimeError: Event loop is closed` is just a consequence there.
So I guess this commit wouldn't fix the problem.

**Comment by erm3nda** [comment]
I am not sure it that applies but:

I am a regular user of httpbin.org/ip for network/ip tests/checks so i can say with no error that some (lot of them) proxies from lists are not allowed to connect to httpbin.org site. I say that to proof that httpbin.org will not accept your requests 100% of times.

Also, if you have some "not much good" vps for run it, it may be threated in the same way. I never had a problem connectin from my regular computer.

httpbin.org is serving an Python software/module that you can download to your server. I think that may reduce the number of requests that can fail, but is just a suggestion.

**Comment by constverum** [comment]
> I say that to proof that httpbin.org will not accept your requests 100% of times.

Therefore, in order to solve the problem, we probably have to add alternative methods to get the real external IP. How it works now with other "proxy judges".

**Comment by erm3nda** [comment]
Adding a secondary httpbin instance in your own domain.

Also, i don't know if proxy judges are used to "get external ip". I didn't read the whole program code and i can't assure it is handled by judged.

In short, i said to not use "domain" httpbin, but same lib hosted in other website that doesn't reject you.

**Comment by gabrielgradinaru** [comment]
Added alternative way to get external ip address.

**Comment by constverum** [comment]
Thank you @gabrielgradinaru! I added the host you suggested and rewrote the function of getting the external IP.

**Pull request closed without merging**
